// src/pages/Assurance.jsx
import React, { useEffect, useState } from 'react';
import { alertsApi, budgetsApi, departmentsApi } from '../api/services';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts';
import { useAuth } from '../context/AuthContext';
import './Dashboard.css';

const fmt = (n) => `₹${Number(n || 0).toLocaleString('en-IN')}`;

const SEV_COLOR = { critical: 'var(--danger)', high: 'var(--danger)', medium: 'var(--warn)', low: 'var(--success)' };
const SEV_ICON  = { critical: '', high: '', medium: '', low: '' };
const SEV_BORDER = { critical: 'var(--danger)', high: 'var(--danger)', medium: 'var(--warn)', low: 'var(--success)' };

export default function Assurance() {
  const { user } = useAuth();
  const [alerts, setAlerts]     = useState([]);
  const [budgets, setBudgets]   = useState([]);
  const [depts, setDepts]       = useState([]);
  const [loading, setLoading]   = useState(true);
  const [filter, setFilter]     = useState('all');

  const load = () => {
    Promise.all([alertsApi.list(), budgetsApi.list(), departmentsApi.list()])
      .then(([a, b, d]) => {
        setAlerts(a.data || []);
        setBudgets(b.data || []);
        setDepts(d.data || []);
      }).finally(() => setLoading(false));
  };
  useEffect(load, []);

  const updateAlert = async (id, action) => {
    if (action === 'acknowledge') await alertsApi.acknowledge(id, user?.username || 'admin');
    if (action === 'resolve')     await alertsApi.resolve(id, user?.username || 'admin');
    if (action === 'dismiss')     await alertsApi.dismiss(id);
    load();
  };

  const filtered = filter === 'all' ? alerts : alerts.filter(a => a.status === filter || a.severity === filter);
  const open     = alerts.filter(a => a.status === 'open');
  const acked    = alerts.filter(a => a.status === 'acknowledged');
  const resolved = alerts.filter(a => a.status === 'resolved');

  const pieData = [
    { name: 'Critical', value: alerts.filter(a => a.severity === 'critical').length, color: '#f43f5e' },
    { name: 'High',     value: alerts.filter(a => a.severity === 'high').length,     color: '#f59e0b' },
    { name: 'Medium',   value: alerts.filter(a => a.severity === 'medium').length,   color: '#d4a017' },
    { name: 'Low',      value: alerts.filter(a => a.severity === 'low').length,      color: '#22d3a0' },
  ].filter(d => d.value > 0);

  const getDeptName = (id) => depts.find(d => d.department_id === id)?.department_name || '—';

  if (loading) return <div className="page-loading"><div className="spinner" /></div>;

  return (
    <div className="page fade-in">
      <div className="ph">
        <div>
          <div className="ph-title">Assurance Monitor</div>
          <div className="ph-sub">Financial compliance alerts — auto-generated by rules engine</div>
        </div>
      </div>

      {open.length > 0 && (
        <div className="alert-strip">
          <div className="pulse-dot" />
          <div><strong>{open.length} Open Alerts</strong> — Immediate review required</div>
        </div>
      )}

      {/* KPIs */}
      <div className="kpi-grid" style={{ gridTemplateColumns: 'repeat(4,1fr)' }}>
        <div className="kpi-card"><div className="kpi-icon"></div><div className="kpi-label">Open</div><div className="kpi-value" style={{ color: 'var(--danger)' }}>{open.length}</div></div>
        <div className="kpi-card"><div className="kpi-icon"></div><div className="kpi-label">Acknowledged</div><div className="kpi-value" style={{ color: 'var(--warn)' }}>{acked.length}</div></div>
        <div className="kpi-card"><div className="kpi-icon"></div><div className="kpi-label">Resolved</div><div className="kpi-value" style={{ color: 'var(--success)' }}>{resolved.length}</div></div>
        <div className="kpi-card"><div className="kpi-icon"></div><div className="kpi-label">Total</div><div className="kpi-value">{alerts.length}</div></div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 20 }}>
        <div>
          {/* Filter tabs */}
          <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
            {['all','open','acknowledged','resolved','critical','high','medium'].map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className={filter === f ? 'btn btn-primary' : 'btn btn-ghost'}
                style={{ padding: '6px 12px', fontSize: 11 }}>
                {f.charAt(0).toUpperCase() + f.slice(1)}
              </button>
            ))}
          </div>

          {/* Alerts List */}
          <div className="card">
            <div className="card-head">
              <div className="card-title">Alerts ({filtered.length})</div>
              <span className="chip chip-danger">{open.length} Open</span>
            </div>
            <div className="card-body">
              {filtered.length === 0 ? (
                <div style={{ textAlign: 'center', color: 'var(--text3)', padding: '20px 0' }}> No alerts matching filter</div>
              ) : (
                <div className="alerts-list">
                  {filtered.map(a => (
                    <div key={a.alert_id} className="alert-item" style={{ '--alc': SEV_BORDER[a.severity] || 'var(--warn)' }}>
                      <div className="alert-ico">{SEV_ICON[a.severity] || ''}</div>
                      <div style={{ flex: 1 }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                          <span style={{ fontSize: 13, fontWeight: 700 }}>{a.title}</span>
                          <span className="pill" style={{ background: 'rgba(212,160,23,0.1)', color: 'var(--accent)', fontSize: 9 }}>{a.alert_code}</span>
                          <span className="pill" style={{ background: a.status === 'open' ? 'rgba(244,63,94,0.1)' : a.status === 'acknowledged' ? 'rgba(245,158,11,0.1)' : 'rgba(34,211,160,0.1)', color: a.status === 'open' ? 'var(--danger)' : a.status === 'acknowledged' ? 'var(--warn)' : 'var(--success)', fontSize: 9 }}>{a.status}</span>
                        </div>
                        <div style={{ fontSize: 12, color: 'var(--text2)', marginBottom: 4 }}>{a.message}</div>
                        {a.recommended_action && (
                          <div style={{ fontSize: 11, color: 'var(--accent)', fontStyle: 'italic' }}> {a.recommended_action}</div>
                        )}
                        <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 4 }}>
                          {a.category} · {a.entity_type} #{a.entity_id} · {getDeptName(a.department_id)} · Due: {a.due_date || '—'}
                        </div>
                        {a.acknowledged_by && (
                          <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)' }}>
                            Actioned by: {a.acknowledged_by}
                          </div>
                        )}
                      </div>
                      {a.status === 'open' && (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, flexShrink: 0 }}>
                          <button className="btn btn-ghost" style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => updateAlert(a.alert_id, 'acknowledge')}>Acknowledge</button>
                          <button className="btn btn-success" style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => updateAlert(a.alert_id, 'resolve')}>Resolve</button>
                          <button className="btn btn-ghost" style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => updateAlert(a.alert_id, 'dismiss')}>Dismiss</button>
                        </div>
                      )}
                      {a.status === 'acknowledged' && (
                        <button className="btn btn-success" style={{ padding: '4px 10px', fontSize: 11, flexShrink: 0 }} onClick={() => updateAlert(a.alert_id, 'resolve')}>Resolve</button>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* Severity Pie */}
          <div className="card">
            <div className="card-head"><div className="card-title">Alert Severity</div></div>
            <div className="card-body">
              {pieData.length > 0 ? (
                <>
                  <ResponsiveContainer width="100%" height={180}>
                    <PieChart>
                      <Pie data={pieData} cx="50%" cy="50%" innerRadius={50} outerRadius={80} dataKey="value" paddingAngle={3}>
                        {pieData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
                      </Pie>
                      <Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 11 }} />
                    </PieChart>
                  </ResponsiveContainer>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 8 }}>
                    {pieData.map((d, i) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
                        <div style={{ width: 8, height: 8, borderRadius: 2, background: d.color, flexShrink: 0 }} />
                        <span style={{ flex: 1, color: 'var(--text2)' }}>{d.name}</span>
                        <span style={{ fontFamily: 'var(--mono)', fontWeight: 600 }}>{d.value}</span>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <div style={{ textAlign: 'center', color: 'var(--text3)', padding: '40px 0' }}> No alerts</div>
              )}
            </div>
          </div>

          {/* Rules Engine Display */}
          <div className="card">
            <div className="card-head"><div className="card-title">Assurance Rules Engine</div><span className="chip chip-accent">Always Active</span></div>
            <div className="card-body" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                { icon: '', code: 'NO_COMMITMENT',          desc: 'Expense without commitment' },
                { icon: '', code: 'HIGH_VALUE_EXPENSE',     desc: 'High-value expense (≥₹10,000)' },
                { icon: '', code: 'EXPENSE_EXCEEDS_COMMITMENT', desc: 'Expense exceeds commitment' },
                { icon: '', code: 'BUDGET_UTILIZATION_80', desc: '80% budget threshold' },
                { icon: '', code: 'BUDGET_EXCEEDED',        desc: 'Budget 100% exceeded' },
                { icon: '', code: 'MULTIPLE_HIGH_EXPENSES', desc: 'Repeated high-value pattern' },
              ].map((rule, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, background: 'var(--surface2)', borderRadius: 8, padding: '10px 14px' }}>
                  <span style={{ fontSize: 16 }}>{rule.icon}</span>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 12, fontWeight: 700 }}>{rule.desc}</div>
                    <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)' }}>{rule.code}</div>
                  </div>
                  <div style={{ width: 32, height: 18, borderRadius: 9, background: 'var(--success)', position: 'relative' }}>
                    <div style={{ position: 'absolute', width: 12, height: 12, borderRadius: '50%', background: '#fff', top: 3, left: 17 }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
