import { useEffect, useState } from 'react';
import { alertsApi, departmentsApi } from '../api/services';
import { PieChart, Pie, Tooltip, ResponsiveContainer } from 'recharts';
import { useAuth } from '../context/AuthContext';
import './Dashboard.css';

const SEV_BORDER = { critical: 'var(--danger)', high: 'var(--warn)', medium: 'var(--accent2)', low: 'var(--success)' };

const STATUS_COLOR = {
  open:         { bg: 'rgba(220,38,38,0.08)',   color: 'var(--danger)' },
  acknowledged: { bg: 'rgba(217,119,6,0.08)',   color: 'var(--warn)' },
  resolved:     { bg: 'rgba(5,150,105,0.08)',   color: 'var(--success)' },
  dismissed:    { bg: 'rgba(61,80,112,0.15)',   color: 'var(--text3)' },
};

const RULES = [
  { code: 'NO_COMMITMENT',           label: 'Expense without approved commitment' },
  { code: 'HIGH_VALUE_EXPENSE',      label: 'High-value expense threshold exceeded' },
  { code: 'EXPENSE_EXCEEDS_COMMITMENT', label: 'Expense amount exceeds linked commitment' },
  { code: 'BUDGET_UTILIZATION_80',   label: 'Budget utilization above 80%' },
  { code: 'BUDGET_EXCEEDED',         label: 'Allocated budget fully exceeded' },
  { code: 'MULTIPLE_HIGH_EXPENSES',  label: 'Repeated high-value spending pattern' },
];

export default function Assurance() {
  const { user } = useAuth();
  const [alerts, setAlerts]   = useState([]);
  const [depts, setDepts]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter]   = useState('all');

  const load = () => {
    Promise.all([alertsApi.list(), departmentsApi.list()])
      .then(([a, d]) => { setAlerts(a.data || []); setDepts(d.data || []); })
      .finally(() => setLoading(false));
  };
  useEffect(load, []);

  const act = async (id, action) => {
    if (action === 'acknowledge') await alertsApi.acknowledge(id, user?.username || 'admin');
    if (action === 'resolve')     await alertsApi.resolve(id, user?.username || 'admin');
    if (action === 'dismiss')     await alertsApi.dismiss(id);
    load();
  };

  const filtered = filter === 'all' ? alerts : alerts.filter(a => a.status === filter || (a.severity||'').toLowerCase() === filter);
  const open     = alerts.filter(a => a.status === 'open').length;
  const acked    = alerts.filter(a => a.status === 'acknowledged').length;
  const resolved = alerts.filter(a => a.status === 'resolved').length;

  const PIE_COLORS = { critical: '#dc2626', high: '#d97706', medium: '#c9970a', low: '#059669' };
  const pieData = Object.entries(PIE_COLORS)
    .map(([key, fill]) => ({ name: key.charAt(0).toUpperCase() + key.slice(1), value: alerts.filter(a => (a.severity||'').toLowerCase() === key).length, fill }))
    .filter(d => d.value > 0);

  const getDeptName = id => depts.find(d => d.department_id === id)?.department_name || '—';

  const filterCount = (f) => {
    if (f === 'all') return alerts.length;
    return alerts.filter(a => a.status === f || (a.severity || '').toLowerCase() === f).length;
  };

  const FILTERS = ['all', 'open', 'acknowledged', 'resolved', 'critical', 'high', 'medium'];

  if (loading) return <div className="page-loading"><div className="spinner" /></div>;

  return (
    <div className="page fade-in">
      <div className="ph">
        <div>
          <div className="ph-title">Risk &amp; Compliance</div>
          <div className="ph-sub">Financial control alerts generated by the rules engine</div>
        </div>
      </div>

      {open > 0 && (
        <div className="alert-strip">
          <div className="pulse-dot" />
          <strong>{open} open alert{open !== 1 ? 's' : ''}</strong>
          <span style={{ color: 'var(--text2)', marginLeft: 4 }}>require immediate review.</span>
        </div>
      )}

      <div className="kpi-grid" style={{ gridTemplateColumns: 'repeat(4,1fr)' }}>
        <KStat label="Open"         val={open}     color="var(--danger)" />
        <KStat label="Acknowledged" val={acked}    color="var(--warn)" />
        <KStat label="Resolved"     val={resolved} color="var(--success)" />
        <KStat label="Total"        val={alerts.length} color="var(--text)" />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 18 }}>
        <div>
          {/* Filter bar */}
          <div style={{ display: 'flex', gap: 6, marginBottom: 14, flexWrap: 'wrap' }}>
            {FILTERS.map(f => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={filter === f ? 'btn btn-primary' : 'btn btn-ghost'}
                style={{ padding: '5px 12px', fontSize: 11, textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: 5 }}
              >
                {f}
                <span style={{
                  fontSize: 10, fontFamily: 'var(--mono)', fontWeight: 600,
                  opacity: filter === f ? 0.8 : 0.5,
                }}>
                  {filterCount(f)}
                </span>
              </button>
            ))}
          </div>

          <div className="card">
            <div className="card-head">
              <div className="card-title">Alerts <span style={{ color: 'var(--text3)', fontWeight: 400 }}>({filtered.length})</span></div>
              <span className="chip chip-danger">{open} Open</span>
            </div>
            <div className="card-body" style={{ padding: 12 }}>
              {filtered.length === 0 ? (
                <div style={{ textAlign: 'center', color: 'var(--text3)', padding: '24px 0', fontSize: 13 }}>
                  No alerts match the selected filter.
                </div>
              ) : (
                <div className="alerts-list">
                  {filtered.map(a => {
                    const sev = (a.severity || '').toLowerCase();
                    const sc  = STATUS_COLOR[a.status] || STATUS_COLOR.open;
                    return (
                      <div
                        key={a.alert_id}
                        className="alert-item"
                        style={{ '--alc': SEV_BORDER[sev] || 'var(--warn)', padding: '12px 14px', gap: 12, display: 'flex', alignItems: 'flex-start' }}
                      >
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 5, flexWrap: 'wrap' }}>
                            <span style={{ fontSize: 12.5, fontWeight: 600 }}>{a.title}</span>
                            <span className="pill" style={{ background: 'rgba(255,220,60,0.1)', color: '#f5d96b', letterSpacing: '0.3px' }}>{a.alert_code.replace(/_/g, ' ')}</span>
                            <span className="pill" style={{ background: sc.bg, color: sc.color }}>
                              {a.status}
                            </span>
                          </div>
                          <div style={{ fontSize: 12, color: 'var(--text2)', lineHeight: 1.5, marginBottom: 5 }}>{a.message}</div>
                          {a.recommended_action && (
                            <div style={{ fontSize: 11, color: 'var(--text3)', fontStyle: 'italic', marginBottom: 4 }}>
                              Recommended: {a.recommended_action}
                            </div>
                          )}
                          <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)' }}>
                            {a.category} &middot; {a.entity_type} #{a.entity_id} &middot; {getDeptName(a.department_id)}
                            {a.due_date && <> &middot; Due {a.due_date}</>}
                          </div>
                          {a.acknowledged_by && (
                            <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 2 }}>
                              Actioned by: {a.acknowledged_by}
                            </div>
                          )}
                        </div>
                        {a.status === 'open' && (
                          <div style={{ display: 'flex', flexDirection: 'column', gap: 5, flexShrink: 0 }}>
                            <button className="btn btn-ghost" style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => act(a.alert_id, 'acknowledge')}>Acknowledge</button>
                            <button className="btn btn-success" style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => act(a.alert_id, 'resolve')}>Resolve</button>
                            <button className="btn btn-ghost"   style={{ padding: '4px 10px', fontSize: 11 }} onClick={() => act(a.alert_id, 'dismiss')}>Dismiss</button>
                          </div>
                        )}
                        {a.status === 'acknowledged' && (
                          <button className="btn btn-success" style={{ padding: '4px 10px', fontSize: 11, flexShrink: 0 }} onClick={() => act(a.alert_id, 'resolve')}>Resolve</button>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* Pie */}
          <div className="card">
            <div className="card-head"><div className="card-title">Alert Severity Breakdown</div></div>
            <div className="card-body">
              {pieData.length > 0 ? (
                <>
                  <ResponsiveContainer width="100%" height={160}>
                    <PieChart>
                      <Pie data={pieData} cx="50%" cy="50%" innerRadius={44} outerRadius={72} dataKey="value" paddingAngle={3} />
                      <Tooltip contentStyle={{ background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 6, fontSize: 11 }} />
                    </PieChart>
                  </ResponsiveContainer>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 7, marginTop: 10 }}>
                    {pieData.map((d, i) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
                        <div style={{ width: 8, height: 8, borderRadius: 2, background: d.fill, flexShrink: 0 }} />
                        <span style={{ flex: 1, color: 'var(--text2)' }}>{d.name}</span>
                        <span style={{ fontFamily: 'var(--mono)', fontWeight: 600 }}>{d.value}</span>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <div style={{ textAlign: 'center', color: 'var(--text3)', padding: '32px 0', fontSize: 13 }}>No alerts</div>
              )}
            </div>
          </div>

          {/* Rules engine */}
          <div className="card">
            <div className="card-head">
              <div className="card-title">Rules Engine</div>
              <span className="chip chip-success">Active</span>
            </div>
            <div className="card-body" style={{ padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {RULES.map((rule, i) => (
                <div key={i} style={{
                  display: 'flex', alignItems: 'center', gap: 10,
                  background: 'var(--surface2)', borderRadius: 6, padding: '9px 12px',
                  border: '1px solid var(--border)',
                }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--success)', flexShrink: 0 }} />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 12, fontWeight: 500 }}>{rule.label}</div>
                    <div style={{ fontSize: 10, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 2 }}>{rule.code.replace(/_/g, ' ')}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function KStat({ label, val, color }) {
  return (
    <div className="kpi-card">
      <div className="kpi-label">{label}</div>
      <div className="kpi-value" style={{ color }}>{val}</div>
    </div>
  );
}
